import brandImage from "../assets/senusa-brand.jpg";
import digitalImage from "../assets/senusa-digital.jpg";
import materialImage from "../assets/senusa-material.jpg";
import studioImage from "../assets/senusa-studio.jpg";
import coffeeImage from "../assets/project-coffee.jpg";
import cyclingImage from "../assets/project-cycling.jpg";
import fashionImage from "../assets/project-fashion.jpg";
import festivalImage from "../assets/project-festival.jpg";
import fragranceImage from "../assets/project-fragrance.jpg";
import furnitureImage from "../assets/project-furniture.jpg";
import hospitalityImage from "../assets/project-hospitality.jpg";
import jewelryImage from "../assets/project-jewelry.jpg";

export type LocalizedText = { id: string; en: string };
export type Project = {
  slug: string; name: string;
  category: "Brand & Commerce" | "Culture & Community" | "Hospitality" | "Digital Product";
  sector: LocalizedText; descriptor: LocalizedText; challenge: LocalizedText;
  approach: LocalizedText; outcome: LocalizedText; services: LocalizedText;
  image: string; gallery: string[]; url: string; year: string;
};

const copy = (sector: LocalizedText, challenge: LocalizedText, approach: LocalizedText, outcome: LocalizedText, services: LocalizedText) => ({ sector, challenge, approach, outcome, services });
const c = (id: string, en: string): LocalizedText => ({ id, en });

export const projects: Project[] = [
  {slug:"arqive",name:"ARQIVE",category:"Digital Product",descriptor:c("Sistem operasi untuk fashion stylist","An operating system for fashion stylists"),image:fashionImage,gallery:[digitalImage,fashionImage,studioImage],url:"https://arqive-senusacorp.lovable.app",year:"2025",...copy(c("Fashion technology","Fashion technology"),c("Stylist membutuhkan satu tempat untuk menemukan koleksi dan mengelola pull tanpa alur yang terpecah.","Stylists needed one place to discover collections and manage pulls without fragmented workflows."),c("Kami menyatukan katalog, pencarian, dan manajemen pull dalam antarmuka editorial yang cepat dipindai.","We united discovery, search, and pull management in a fast, editorial interface."),c("Platform yang membuat koleksi lebih mudah ditemukan dan kolaborasi stylist lebih tertata.","A platform that makes collections easier to discover and stylist collaboration more organized."),c("Product strategy · UI/UX · Development","Product strategy · UI/UX · Development"))},
  {slug:"nusa-living",name:"NUSA Living",category:"Brand & Commerce",descriptor:c("Ruang digital untuk kriya Jepara","A digital home for Jepara craft"),image:furnitureImage,gallery:[furnitureImage,materialImage,studioImage],url:"https://nusa-senusacorp.lovable.app",year:"2025",...copy(c("Furnitur & kriya","Furniture & craft"),c("Keahlian pengrajin Jepara perlu terasa premium tanpa kehilangan kehangatan dan asal-usulnya.","Jepara craftsmanship needed to feel premium without losing its warmth and provenance."),c("Ruang, material, dan detail sambungan menjadi bahasa visual untuk katalog yang tenang dan tak lekang waktu.","Space, material, and joinery became the visual language for a quiet, timeless catalogue."),c("Koleksi lebih mudah dijelajahi dengan cerita craft yang kuat pada setiap produk.","A more browsable collection with a strong craft story around every product."),c("Brand direction · E-commerce · Art direction","Brand direction · E-commerce · Art direction"))},
  {slug:"rona-festival",name:"RONA Festival",category:"Culture & Community",descriptor:c("Festival musik dalam lanskap visual","Music festival in a visual landscape"),image:festivalImage,gallery:[festivalImage,brandImage,studioImage],url:"https://rona-senusacorp.lovable.app",year:"2025",...copy(c("Musik & budaya","Music & culture"),c("Program multidisiplin membutuhkan identitas yang ekspresif sekaligus mudah dipahami pengunjung.","A multidisciplinary program needed an expressive identity that remained easy to navigate."),c("Warna senja, ritme tipografi, dan struktur jadwal dirangkai menjadi pengalaman festival yang hidup.","Sunset color, typographic rhythm, and program structure became a vivid festival experience."),c("Satu pusat informasi yang membawa energi acara dari pengumuman hingga hari festival.","One information hub carrying the event energy from announcement to festival day."),c("Campaign · Website · Visual system","Campaign · Website · Visual system"))},
  {slug:"niskala-aruna",name:"Niskala Aruna",category:"Hospitality",descriptor:c("Hospitalitas dengan jiwa Jawa","Hospitality with a Javanese soul"),image:hospitalityImage,gallery:[hospitalityImage,materialImage,studioImage],url:"https://niskalaaruna-senusacorp.lovable.app",year:"2025",...copy(c("Boutique hospitality","Boutique hospitality"),c("Pengalaman menginap yang personal perlu diterjemahkan ke digital tanpa terasa seperti katalog hotel biasa.","A personal stay needed a digital expression that did not feel like a typical hotel catalogue."),c("Narasi ruang, tekstur kayu, dan tempo yang lapang membangun perjalanan pemesanan yang hangat.","Spatial storytelling, timber textures, and generous pacing shaped a warm booking journey."),c("Kehadiran digital yang menonjolkan ketenangan tempat sekaligus memudahkan tamu merencanakan kunjungan.","A digital presence that conveys calm while helping guests plan their stay."),c("Positioning · Website · Content direction","Positioning · Website · Content direction"))},
  {slug:"senja-parfum",name:"SÉNJA PARFUM",category:"Brand & Commerce",descriptor:c("Aroma Nusantara saat matahari turun","Archipelago scents at sundown"),image:fragranceImage,gallery:[fragranceImage,brandImage,materialImage],url:"https://wangi-indah-digital-senusacorp.lovable.app",year:"2025",...copy(c("Parfum","Fragrance"),c("Aroma yang memadukan bunga dingin dan cahaya jingga membutuhkan dunia visual yang sama berlapisnya.","A scent balancing cool florals and amber light needed an equally layered visual world."),c("Kontras air, bunga, dan warna senja membentuk pengalaman produk yang sensorial dan sinematik.","Contrasts of water, florals, and sunset color shaped a sensory, cinematic product experience."),c("Peluncuran digital yang membuat karakter aroma terasa bahkan sebelum botol dibuka.","A digital launch that makes the scent character tangible before the bottle is opened."),c("Creative direction · Campaign site · Commerce","Creative direction · Campaign site · Commerce"))},
  {slug:"fenomena-bike",name:"Fenomena Bike",category:"Culture & Community",descriptor:c("Cerita jalanan komunitas sepeda","Street stories from a cycling community"),image:cyclingImage,gallery:[cyclingImage,studioImage,brandImage],url:"https://fenomenabike.lovable.app",year:"2025",...copy(c("Komunitas sepeda","Cycling community"),c("Komunitas yang tumbuh organik membutuhkan rumah digital yang sama jujur dan energik dengan perjalanan mereka.","An organically grown community needed a digital home as honest and energetic as its rides."),c("Fotografi dokumenter, kontras kuat, dan aksen berani menyatukan cerita anggota, rute, dan agenda.","Documentary photography, hard contrast, and bold accents connect member stories, routes, and events."),c("Arsip komunitas yang hidup serta pintu masuk yang jelas bagi pesepeda baru.","A living community archive and a clear entry point for new riders."),c("Community platform · Editorial · Development","Community platform · Editorial · Development"))},
  {slug:"ruang-seduh",name:"Ruang Seduh",category:"Hospitality",descriptor:c("Kopi, proses, dan percakapan","Coffee, process, and conversation"),image:coffeeImage,gallery:[coffeeImage,materialImage,studioImage],url:"https://ruangsenduh-senusacorp.lovable.app",year:"2025",...copy(c("Coffee shop","Coffee shop"),c("Budaya meracik yang teliti perlu diceritakan secara ramah kepada penikmat kopi sehari-hari.","A meticulous brewing culture needed an approachable story for everyday coffee drinkers."),c("Detail alat, biji, dan ritual seduh memandu pengunjung dari cerita rasa menuju menu.","Tools, beans, and brewing rituals guide visitors from flavor stories to the menu."),c("Website hangat yang memperkuat pengalaman kedai dan mengundang percakapan.","A warm website that extends the café experience and invites conversation."),c("Storytelling · Website · Photography direction","Storytelling · Website · Photography direction"))},
  {slug:"aspal",name:"ASPAL",category:"Brand & Commerce",descriptor:c("Streetwear dari hutan beton","Streetwear from the concrete jungle"),image:fashionImage,gallery:[fashionImage,brandImage,studioImage],url:"https://aspal-senusacorp.lovable.app",year:"2025",...copy(c("Streetwear","Streetwear"),c("Label independen membutuhkan etalase yang terasa mentah, cepat, dan punya sikap.","An independent label needed a storefront that felt raw, fast, and opinionated."),c("Komposisi brutal, material urban, dan alur belanja ringkas menjadi bahasa Hutan Beton.","Brutal composition, urban materials, and a concise shopping flow became the language of Hutan Beton."),c("Koleksi lebih tegas, mudah dibeli, dan tetap terasa seperti bagian dari kultur jalanan.","A sharper, shoppable collection that remains rooted in street culture."),c("E-commerce · Art direction · Development","E-commerce · Art direction · Development"))},
  {slug:"selaras",name:"SÉLARAS",category:"Brand & Commerce",descriptor:c("Busana tenang dalam gerak","Quiet clothing in motion"),image:fashionImage,gallery:[fashionImage,materialImage,brandImage],url:"https://selaras-senusacorp.lovable.app",year:"2025",...copy(c("Fashion","Fashion"),c("Koleksi bernuansa lembut membutuhkan presentasi yang menonjolkan potongan dan gerak tanpa distraksi.","A softly nuanced collection needed a presentation focused on cut and movement without distraction."),c("Ruang putih, ritme editorial, dan detail kain menciptakan katalog yang kontemporer dan tenang.","White space, editorial rhythm, and fabric detail create a contemporary, calm catalogue."),c("Pengalaman koleksi yang memberi tiap look ruang untuk bernapas dan mudah dijelajahi.","A collection experience that gives every look room to breathe and remains easy to explore."),c("Digital flagship · Lookbook · Commerce","Digital flagship · Lookbook · Commerce"))},
  {slug:"morphe",name:"MORPHÉ",category:"Brand & Commerce",descriptor:c("Studi eksperimental dalam perak","Experimental studies in silver"),image:jewelryImage,gallery:[jewelryImage,materialImage,brandImage],url:"https://morphe-senusacorp.lovable.app",year:"2025",...copy(c("Perhiasan","Jewelry"),c("Bentuk perak eksperimental harus tampil sebagai objek seni sekaligus produk yang dapat dimiliki.","Experimental silver forms needed to read as both art objects and attainable products."),c("Makro material, bayangan tajam, dan tata letak galeri menempatkan setiap karya sebagai pusat perhatian.","Material macros, hard shadows, and gallery layouts place each piece at center stage."),c("Etalase digital yang menaikkan nilai koleksi tanpa menyulitkan proses pembelian.","A digital showcase that elevates the collection without complicating purchase."),c("Brand world · E-commerce · Campaign","Brand world · E-commerce · Campaign"))},
  {slug:"virel-house",name:"VIREL House",category:"Hospitality",descriptor:c("Singgah, pulih, dan menikmati","Stay, restore, and taste"),image:hospitalityImage,gallery:[hospitalityImage,materialImage,studioImage],url:"https://virel-senusacorp.lovable.app",year:"2025",...copy(c("Retreat & dining","Retreat & dining"),c("Akomodasi dan pengalaman kuliner perlu hadir sebagai satu perjalanan yang utuh.","Accommodation and dining needed to appear as one cohesive journey."),c("Kami menyusun cerita hari demi hari, dari ruang beristirahat hingga meja makan.","We shaped a day-by-day story, from restorative rooms to the dining table."),c("Situs yang membangun rasa ingin tinggal lebih lama dan memudahkan perencanaan kunjungan.","A site that inspires longer stays and makes planning effortless."),c("Experience design · Website · Booking journey","Experience design · Website · Booking journey"))},
  {slug:"villa-anggrek",name:"Villa Anggrek",category:"Hospitality",descriptor:c("Tempat pulang di Senggigi","A place to return to in Senggigi"),image:hospitalityImage,gallery:[hospitalityImage,studioImage,materialImage],url:"https://hotelangrek-senusacorp.lovable.app",year:"2025",...copy(c("Private villa","Private villa"),c("Villa intim membutuhkan kehadiran online yang terasa personal, bukan seperti platform pemesanan massal.","An intimate villa needed an online presence that felt personal, not like a mass booking platform."),c("Cahaya, detail ruang, dan informasi lokal dirangkai dalam perjalanan yang sederhana.","Light, room details, and local information were woven into a simple journey."),c("Tamu memahami suasana, fasilitas, dan lokasi sebelum memulai reservasi.","Guests understand the atmosphere, amenities, and location before starting a reservation."),c("Website · Content design · Inquiry flow","Website · Content design · Inquiry flow"))},
  {slug:"north-coffee",name:"NORTH / COFFEE",category:"Hospitality",descriptor:c("Roastery kecil dari Bali","A small-batch roastery from Bali"),image:coffeeImage,gallery:[coffeeImage,brandImage,materialImage],url:"https://north-senusacorp.lovable.app",year:"2025",...copy(c("Coffee roastery","Coffee roastery"),c("Roastery spesialis membutuhkan cerita produk yang presisi namun tidak terasa kaku.","A specialty roastery needed precise product storytelling without feeling rigid."),c("Objek seduh, asal biji, dan catatan rasa disajikan seperti jurnal produk yang terkurasi.","Brewing objects, origins, and tasting notes are presented as a curated product journal."),c("Identitas digital yang terasa berbeda dan memudahkan pelanggan memilih kopi.","A distinctive digital identity that helps customers choose their coffee."),c("Brand system · E-commerce · Editorial","Brand system · E-commerce · Editorial"))},
  {slug:"aroma-27",name:"AROMA/27",category:"Brand & Commerce",descriptor:c("Eksperimen aroma yang berani","A bold experiment in scent"),image:fragranceImage,gallery:[fragranceImage,materialImage,brandImage],url:"https://wangi-indah-desain-senusacorp.lovable.app",year:"2025",...copy(c("Fragrance concept","Fragrance concept"),c("Lini parfum konseptual membutuhkan sistem yang cukup berani untuk membedakan setiap eksperimen aroma.","A conceptual fragrance line needed a system bold enough to distinguish each scent experiment."),c("Nomor, warna, dan komposisi makro menjadi kode visual yang fleksibel di seluruh koleksi.","Numbers, color, and macro compositions became a flexible visual code across the collection."),c("Sistem identitas yang mudah diperluas untuk rilisan dan kampanye baru.","An identity system designed to expand across future releases and campaigns."),c("Identity · Packaging direction · Campaign","Identity · Packaging direction · Campaign"))},
  {slug:"ruang-rupa",name:"Ruang Rupa",category:"Culture & Community",descriptor:c("Jurnal mode dan material","A journal of fashion and material"),image:fashionImage,gallery:[fashionImage,studioImage,brandImage],url:"https://ruangrupa-senusacorp.lovable.app",year:"2025",...copy(c("Fashion journal","Fashion journal"),c("Editorial independen membutuhkan sistem yang dapat menampung esai, visual eksperimental, dan arsip.","An independent editorial needed a system for essays, experimental visuals, and an archive."),c("Grid majalah, tipografi berkarakter, dan transisi visual menyatukan konten yang beragam.","Magazine grids, characterful typography, and visual transitions connect diverse content."),c("Jurnal digital yang terasa hidup tanpa mengorbankan kenyamanan membaca.","A digital journal that feels alive without compromising readability."),c("Editorial design · CMS · Development","Editorial design · CMS · Development"))},
  {slug:"sela",name:"SELA",category:"Brand & Commerce",descriptor:c("Busana uniseks untuk keseharian","Unisex clothing for everyday life"),image:fashionImage,gallery:[fashionImage,materialImage,studioImage],url:"https://sela-senuacorp.lovable.app",year:"2025",...copy(c("Unisex fashion","Unisex fashion"),c("Busana sehari-hari perlu tampil sederhana, inklusif, dan tetap memiliki karakter kuat.","Everyday clothing needed to feel simple, inclusive, and still strongly recognizable."),c("Gerak tubuh, siluet, dan bahasa yang langsung membentuk pengalaman belanja tanpa sekat gender.","Movement, silhouette, and direct language shape a genderless shopping experience."),c("Katalog yang mudah digunakan dan tetap menyampaikan filosofi hidup pelan.","An easy catalogue that still communicates a slower-living philosophy."),c("E-commerce · UX writing · Art direction","E-commerce · UX writing · Art direction"))},
  {slug:"penulis",name:"PENULIS",category:"Culture & Community",descriptor:c("Portofolio sastra Indonesia","An Indonesian literary portfolio"),image:studioImage,gallery:[studioImage,brandImage,materialImage],url:"https://pesona-desain-web-senusacorp.lovable.app",year:"2025",...copy(c("Portofolio kreatif","Creative portfolio"),c("Karya sastra, profil, dan agenda perlu tersusun rapi tanpa menghilangkan kepribadian penulis.","Literary works, profile, and events needed structure without losing the writer's voice."),c("Tipografi menjadi pemeran utama dengan navigasi ringkas dan ruang baca yang nyaman.","Typography takes the lead with concise navigation and a comfortable reading space."),c("Portofolio profesional yang memudahkan editor dan pembaca menemukan karya penting.","A professional portfolio helping editors and readers discover key work."),c("Portfolio · Editorial design · Development","Portfolio · Editorial design · Development"))},
];

export const assets = { brandImage, digitalImage, materialImage, studioImage };