import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { useLanguage } from "../lib/i18n";
import { assets, projects } from "../lib/site-data";

export const Route = createFileRoute("/")({
  staticData: { sitemap: true },
  head: () => ({ meta: [
    { title: "SenusaCorp — Creative & Digital Agency Indonesia" },
    { name: "description", content: "Website, identitas brand, dan aplikasi bisnis yang dirancang dengan hati dan dibangun untuk bekerja." },
    { property: "og:title", content: "SenusaCorp — Ideas made useful" },
    { property: "og:description", content: "Creative and digital agency for websites, brands, CRM, and HRM." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: Home,
});

function Home() {
  const { language } = useLanguage(); const id = language === "id";
  const featured = projects.slice(0, 5);
  return <>
    <section className="hero editorial-hero">
      <div className="hero-top"><div><p className="eyebrow">SenusaCorp · Creative & Digital Agency</p><h1>{id ? <>IDE JADI <em>NYATA.</em></> : <>IDEAS MADE <em>USEFUL.</em></>}</h1></div><div><p className="hero-copy">{id ? "Kami merancang identitas, website, dan sistem digital yang tidak hanya terlihat bagus—tetapi bekerja nyata." : "We design identities, websites, and digital systems that don't just look good—they work."}</p><Link to="/work" className="button button-light">{id ? "Lihat karya" : "See our work"}<ArrowUpRight size={16}/></Link></div></div>
      <div className="hero-media"><img src={assets.studioImage} width="1600" height="1008" alt={id ? "Proses kreatif SenusaCorp di studio" : "SenusaCorp creative process in the studio"}/><span className="media-caption">01 / {id?"Studio & proses":"Studio & process"}</span></div>
      <div className="floating-card"><img src={assets.digitalImage} width="1408" height="1008" alt="Digital product interface"/><b>CRM / HRM</b><small>Product systems · 2026</small></div><span className="scroll-note">{id ? "Gulir untuk jelajah" : "Scroll to explore"}</span>
    </section>
    <div className="ticker"><div className="ticker-track"><span>IMAGINE <i>·</i> DESIGN <i>·</i> BUILD <i>·</i> GROW <i>·</i></span><span>IMAGINE <i>·</i> DESIGN <i>·</i> BUILD <i>·</i> GROW <i>·</i></span></div></div>
    <section className="section manifesto"><div className="section-header"><p className="eyebrow">(01) {id ? "Tentang kami" : "About us"}</p><div><h2>{id ? "Karya dengan tujuan." : "Craft with purpose."}</h2></div></div><p className="section-lead">{id ? "SenusaCorp adalah studio kreatif dan teknologi Indonesia. Kami menyatukan strategi, desain, dan engineering untuk membantu bisnis tampil lebih percaya diri dan berjalan lebih efisien." : "SenusaCorp is an Indonesian creative and technology studio. We unite strategy, design, and engineering to help businesses show up confidently and operate efficiently."}</p><div className="stats-strip"><div><b>17</b><span>{id?"karya digital":"digital works"}</span></div><div><b>04</b><span>{id?"disiplin inti":"core disciplines"}</span></div><div><b>02</b><span>{id?"bahasa":"languages"}</span></div><div><b>01</b><span>{id?"partner terpadu":"integrated partner"}</span></div></div></section>
    <section className="section why-band"><div className="section-header"><p className="eyebrow">(02) {id ? "Kenapa penting" : "Why it matters"}</p><h2>{id ? "Bisnis tanpa website, hilang pelanggan." : "No website means lost customers."}</h2></div><p className="section-lead">{id ? "Sebelum membeli atau bekerja sama, orang mencari nama bisnis Anda di Google. Kalau tidak ketemu, mereka pindah ke pesaing." : "Before buying, people search your business on Google. If they can't find you, they go to a competitor."}</p><div className="why-grid">{[
      [id?"Dipercaya sejak klik pertama":"Trusted from the first click", id?"Website resmi membuat bisnis Anda terlihat serius dan profesional, bukan sekadar akun media sosial.":"An official website makes your business look serious and professional, not just a social media account."],
      [id?"Jualan jalan 24 jam":"Selling around the clock", id?"Calon pelanggan bisa melihat produk, harga, dan langsung menghubungi Anda kapan saja—termasuk saat Anda tidur.":"Customers can see your products, prices, and contact you anytime—even while you sleep."],
      [id?"Milik Anda sendiri":"Fully yours", id?"Akun media sosial bisa dibatasi atau hilang. Website dan data pelanggan tetap jadi aset milik bisnis Anda.":"Social accounts can be limited or lost. Your website and customer data stay your own asset."],
      [id?"Ditemukan di pencarian":"Found on search", id?"Kami rapikan struktur halaman agar bisnis Anda muncul saat orang mencari jasa atau produk seperti milik Anda.":"We structure every page so your business appears when people search for what you offer."],
      [id?"Kerja tim lebih rapi":"Tidier team work", id?"Pesanan, data klien, dan absensi bisa dipindahkan dari catatan manual ke sistem digital yang gampang dipakai.":"Orders, client data, and attendance move from manual notes into a system that is easy to use."],
      [id?"Naik kelas, siap tumbuh":"Ready to scale", id?"Mulai dari halaman sederhana, lalu tambah fitur toko, booking, atau aplikasi internal saat bisnis membesar.":"Start with a simple page, then add store, booking, or internal apps as the business grows."],
    ].map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section className="section section-surface compare-band"><div className="section-header"><p className="eyebrow">(03) {id ? "Bandingkan" : "Compare"}</p><h2>{id ? "Harga jujur, hasil serius." : "Honest price, serious result."}</h2></div><p className="section-lead">{id ? "Banyak agensi mematok harga tinggi dan proses lama. Kami buat digitalisasi bisnis Indonesia jadi terjangkau dan cepat." : "Many agencies charge high and work slow. We make digitalising Indonesian businesses affordable and fast."}</p><div className="compare-table"><div className="compare-head"><span>{id?"Yang dibandingkan":"What we compare"}</span><span>{id?"Agensi umum":"Typical agency"}</span><span>{id?"Jasa template murah":"Cheap template service"}</span><b>SenusaCorp</b></div>{[
      [id?"Harga mulai":"Starting price", "Rp5jt – Rp15jt+", "Rp500rb – Rp1jt", "Rp200rb"],
      [id?"Website bisnis lengkap":"Full business website", "Rp15jt – Rp40jt", id?"Tidak tersedia":"Not available", "Rp1,5jt – Rp4,5jt"],
      [id?"Waktu pengerjaan":"Delivery time", id?"1 – 3 bulan":"1 – 3 months", id?"1 minggu, seadanya":"1 week, as-is", id?"3 – 14 hari":"3 – 14 days"],
      [id?"Desain":"Design", id?"Custom, biaya besar":"Custom, high cost", id?"Template pasaran":"Off-the-shelf template", id?"Custom sesuai brand":"Custom to your brand"],
      [id?"Kecepatan di ponsel":"Speed on phones", id?"Tergantung tim":"Depends on the team", id?"Sering berat":"Often slow", id?"Cepat & ringan":"Fast and light"],
      [id?"Aplikasi bisnis (CRM/HRM)":"Business apps (CRM/HRM)", id?"Proyek terpisah, mahal":"Separate, expensive project", id?"Tidak ada":"None", id?"Satu tim yang sama":"Same team, one flow"],
      [id?"Biaya tersembunyi":"Hidden fees", id?"Sering ada":"Common", id?"Biaya tambah fitur":"Fees for every add-on", id?"Tidak ada, rincian jelas":"None, clear breakdown"],
    ].map(r=><div className="compare-row" key={r[0]}><span>{r[0]}</span><span>{r[1]}</span><span>{r[2]}</span><b>{r[3]}</b></div>)}</div><p className="compare-note">{id?"Perbandingan harga adalah kisaran umum pasar Indonesia sebagai gambaran, bukan penawaran resmi pihak lain.":"Competitor ranges are common Indonesian market estimates for reference only, not official quotes."}</p></section>
    <section className="section segments-band"><div className="section-header"><p className="eyebrow">(04) {id ? "Untuk siapa" : "Who it's for"}</p><h2>{id ? "UMKM & profesional naik kelas." : "Small business, big presence."}</h2></div><div className="segment-grid">{[
      [id?"UMKM & toko":"Small business & shops", id?"Warung, kuliner, fesyen, kerajinan, jasa lokal.":"Food, fashion, crafts, and local services.", ["Rp200rb","Rp1,5jt"], id?["Halaman siap tayang cepat","Katalog produk & harga","Tombol pesan langsung"]:["Fast page, live quickly","Product and price catalogue","Direct order button"]],
      [id?"Profesional & personal brand":"Professionals & personal brands", id?"Konsultan, arsitek, fotografer, dokter, penulis.":"Consultants, architects, photographers, doctors, writers.", ["Rp1,5jt","Rp4,5jt"], id?["Portofolio & profil rapi","Jadwal & formulir klien","Muncul di pencarian nama"]:["Clean portfolio and profile","Booking and client forms","Findable by your name"]],
      [id?"Perusahaan & tim":"Companies & teams", id?"Perusahaan berkembang yang butuh sistem internal.":"Growing companies that need internal systems.", ["Rp4,5jt", id?"Sesuai lingkup":"Scoped"], id?["Company profile berwibawa","CRM, HRM, dashboard","Integrasi data & laporan"]:["Authoritative company profile","CRM, HRM, dashboards","Data and reporting integration"]],
    ].map(([t,d,range,items])=><article className="segment" key={t as string}><h3>{t}</h3><p>{d}</p><div className="segment-price"><small>{id?"Kisaran":"Range"}</small><b>{(range as string[])[0]} — {(range as string[])[1]}</b></div><ul>{(items as string[]).map(x=><li key={x}>{x}</li>)}</ul></article>)}</div><div className="section-action"><Link to="/contact" className="button button-dark">{id?"Konsultasi gratis":"Free consultation"}<ArrowUpRight size={16}/></Link><Link to="/pricing" className="button button-ghost">{id?"Lihat semua paket":"See all packages"}</Link></div></section>
    <section className="section work-showcase"><div className="section-header"><p className="eyebrow">(05) {id ? "Karya pilihan" : "Selected work"}</p><h2>{id ? "Bukti, bukan janji." : "Proof, not promises."}</h2></div><div className="work-grid">{featured.map((project,index) => <Link key={project.slug} to="/work/$slug" params={{slug:project.slug}} className="project-card"><div className="project-image"><img src={project.image} loading="lazy" width="1408" height="1008" alt={project.name}/><span className="project-count">0{index+1}</span></div><div className="project-meta"><div><small>{project.category} · {project.year}</small><h3>{project.name}</h3></div><p>{project.descriptor[language]}</p></div></Link>)}</div><div className="section-action"><Link to="/work" className="button button-dark">{id ? "Semua karya" : "All work"}<ArrowUpRight size={16}/></Link></div></section>

    <section className="section section-dark"><div className="section-header"><p className="eyebrow">(03) {id ? "Kemampuan" : "Capabilities"}</p><h2>{id ? "Dari citra hingga sistem." : "From image to system."}</h2></div><div className="services-list">{[
      ["01", id?"Brand & Identitas":"Brand & Identity", id?"Strategi, nama, identitas visual, dan panduan yang membuat brand konsisten.":"Strategy, naming, visual identity, and guidelines for a consistent brand."],
      ["02", id?"Website & Commerce":"Websites & Commerce", id?"Portofolio, company profile, landing page, dan toko online yang cepat.":"Fast portfolios, company profiles, landing pages, and online stores."],
      ["03", id?"Aplikasi Bisnis":"Business Applications", id?"CRM, HRM, dashboard, dan sistem khusus untuk alur kerja Anda.":"CRM, HRM, dashboards, and custom systems for your workflows."],
      ["04", id?"Kampanye Digital":"Digital Campaigns", id?"Konsep, konten, dan pengalaman digital untuk menarik perhatian.":"Concepts, content, and digital experiences designed to earn attention."],
    ].map(([n,t,d])=><div className="service-row" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><ArrowUpRight/></div>)}</div></section>
    <section className="section"><div className="image-split"><div className="image-pill"><img src={assets.brandImage} loading="lazy" width="1408" height="1008" alt={id?"Pengembangan identitas brand Indonesia":"Indonesian brand identity development"}/></div><div><p className="eyebrow">(04) {id?"Cara kerja":"How we work"}</p><h2 className="section-lead">{id?"Dekat, transparan, dan bergerak cepat—tanpa mengorbankan detail.":"Close, transparent, and fast-moving—without sacrificing detail."}</h2><div className="process-mini">{(id?["Temukan","Arahkan","Wujudkan","Tumbuhkan"]:["Discover","Direct","Deliver","Grow"]).map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3></article>)}</div><Link to="/process" className="button button-dark">{id?"Lihat proses":"Our process"}<ArrowUpRight size={16}/></Link></div></div></section>
    <section className="section section-lime"><div className="price-callout"><div><p className="eyebrow">{id?"Mulai sederhana. Tumbuh kemudian.":"Start simple. Grow from there."}</p><h2><span>{id?"Mulai dari":"Starting from"}</span>Rp200K</h2></div><div><p>{id?"Paket Quick Start untuk kebutuhan digital yang ringkas dan jelas. Solusi bisnis lengkap dihitung sesuai lingkup.":"Quick Start for a focused, clearly defined digital need. Full business solutions are scoped separately."}</p><Link to="/pricing" className="button button-dark">{id?"Lihat paket":"See packages"}<ArrowUpRight size={16}/></Link></div></div></section>
    <section className="section section-dark"><div className="section-header"><p className="eyebrow">(05) {id?"Kata mereka":"Kind words"}</p><h2>{id?"Kolaborasi yang terasa." : "Collaboration you can feel."}</h2></div><div className="quote-grid"><div className="quote"><blockquote>“{id?"SenusaCorp menangkap karakter brand kami dan mengubahnya menjadi pengalaman digital yang jauh lebih matang.":"SenusaCorp captured our brand's character and turned it into a much more mature digital experience."}”</blockquote><cite>— Partner brand, Indonesia</cite></div><div className="quote"><blockquote>“{id?"Prosesnya jelas, komunikasinya enak, dan hasil akhirnya bukan sekadar cantik—benar-benar bisa dipakai.":"The process was clear, communication was easy, and the result wasn't merely beautiful—it was genuinely useful."}”</blockquote><cite>— Product collaborator, Indonesia</cite></div></div></section>
  </>;
}